# Generated by Django 4.1.7 on 2023-04-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0037_alter_product_instagram_alter_product_skype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscrib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
