# Generated by Django 4.1.7 on 2023-04-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0046_alter_reviewmy_image_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmy',
            name='image_avatar',
            field=models.ImageField(blank=True, default='anonim.jpg', null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
