# Generated by Django 4.1.7 on 2023-04-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0048_alter_reviewmy_image_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_articl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('mutetext', models.CharField(max_length=50, verbose_name='Mute')),
                ('full_text', models.TextField(max_length=1000, verbose_name='Articl')),
                ('categories', models.CharField(choices=[('Business', 'Business'), ('Events', 'Events'), ('Documentation', 'Documentation')], default='Events', max_length=50)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Publication date')),
                ('news_image', models.ImageField(blank=True, default='images/news.jpg', null=True, upload_to='images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
