# Generated by Django 4.1.7 on 2023-04-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0049_news_articl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_articl',
            name='categories',
            field=models.CharField(choices=[('Business', 'business'), ('Events', 'events'), ('Documentation', 'documentation')], default='Events', max_length=50),
        ),
    ]
