# Generated by Django 4.1.7 on 2023-04-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0050_alter_news_articl_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_articl',
            name='categories',
            field=models.CharField(choices=[('business', 'business'), ('events', 'events'), ('documentation', 'documentation')], default='events', max_length=50),
        ),
    ]
